# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tomáš Gavenčiak Homepage
email: gavento@ucw.cz
description: > # this means to ignore newlines until "baseurl:"
    Homepage of Tomáš Gavenčiak: contacts, research, teaching, projects and personal info.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gavento.ucw.cz" # the base hostname & protocol for your site
github_username:  gavento
#theme: minimal-mistakes-jekyll
theme: jekyll-theme-kagami
color_scheme: github
    
# Build settings
markdown: kramdown
mathjax: true
